### PR TITLE
Add support for forwarding the controller connection.

### PR DESCRIPTION
**Pull request by frankban**
This fixes the Juju GUI charm in Juju 2.

### CODE REVIEW

**Comment by frankban** [comment]
QA: deploy the charm and ensure the GUI can properly connect and log into Juju, in both Juju 1 and Juju 2.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/173/
Test PASSed.

**Comment by bac** [comment]
There is confusion in the ranks about our support of deploying Juju GUI as a charm with Juju 2. By addressing this bug it seems clear that we do want to continue with that support. Let's ensure everyone knows this is a valid deployment method.

**Comment by makyo** [comment]
QA okay :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
