### PR TITLE
Add gisf-enabled -> jujugui.gisf setting.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by bac** [comment]
QA:

```
juju set juju-gui gisf-enabled=True
```
And then observe the production.ini file changed.

**Comment by hatched** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/93/
Test PASSed.

**Comment by jaycee** [comment]
:+1: on code but I'm dubious about it being done, tbh.

**Comment by jaycee** [comment]
I have been informed by the people who would know to be less dubious, so consider this a much less reserved :+1: :)

**Comment by hatched** [comment]
Thanks @bac :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
