### PR TITLE
Fix additional charmhelper conversion issues.

### PR DESCRIPTION
**Pull request by bac**
A couple of hooks were missed and the wrong get_config was chosen.

### CODE REVIEW

**Comment by bac** [comment]
QA:

For juju 1 and juju 2:
```
juju bootstrap && make deploy
```

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/66/
Test PASSed.

**Comment by makyo** [comment]
:+1:

**Comment by jrwren** [comment]
:+1: QA works. I used juju 1.25.3.

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
