### PR TITLE
Add new jujugui dependencies to deps directory.

### PR DESCRIPTION
**Pull request by bac**
QA:

```
juju bootstrap ec2
make deploy
juju ssh juju-gui/0
python
  >> import jujugui
```

Should not blow up.

### CODE REVIEW

**Comment by frankban** [comment]
:+1: thank you!

**Comment by frankban** [comment]
QA ok.

**Comment by makyo** [comment]
:+1:

**Comment by hatched** [comment]
Won't this mean we'll have to update the downloadcache and the charm every time we update a dependency? Curious why not require a build step in the charm to download the deps?

**Comment by bac** [comment]
Thanks for the reviews and the discussion on IRC @hatched. We might get there with what you suggest but not right now.

:shipit:

**Pull request merged**
