### PR TITLE
Support for passing insecure mode. Update juju-gui package.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/40/
Test PASSed.

**Comment by jaycee** [comment]
:+1: 

This was already QAed as part of another branch, so QA OK.

**Comment by frankban** [comment]
:+1:

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
