### PR TITLE
Remove unused code.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

Deploy the charm to your env (or envs) of choice. Make sure deployment and configuration change work.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/16/
Test PASSed.

**Comment by jrwren** [comment]
:+1: QA worked well. I did the typical mariadb _ wordpress demo and things deployed from charmstore. I changed the debug config value in wordpress and confirmed that /_debug/info.php was not available and then it was.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
