### PR TITLE
Supply empty string to apiaddress when in sandbox so gui can start up w/o juju.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

* `make deploy` to your bootstrapped env of choice.
* `juju set juju-gui sandbox=true`
Ensure the gui can load in sandbox.

*`juju set juju-gui sandbox=false`
Open the gui again and make sure things work (e.g. this didn't bork websockets normal operation).

**Comment by bac** [comment]
:+1:

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/12/
Test FAILed.

**Comment by bac** [comment]
QA-OK :fried_shrimp: :chicken:

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/13/
Test FAILed.

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge/5

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/14/
Test PASSed.

**Pull request merged**
