### PR TITLE
Fix charm not deploying correctly on xenial.

### PR DESCRIPTION
**Pull request by frankban**
This was due to a pip install error.
Also:
- print the password when "make deploy" completes;
- add additional clean-up of unused helper functions;
- fix "make help" command descriptions.

QA:
Ensure the GUI charm can be correctly deployed:
run both "make deploy" and "make deploy SERIES=trusty".
Also check that the password is correctly printed when
the unit is ready.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/131/
Test PASSed.

**Comment by frankban** [comment]
FOrgot to mention in the QA section. Before running "make deploy" you should put a recent GUI release bz2 inside the releases directory.

**Comment by jaycee** [comment]
Code looks good. :+1: 

QAing now.

**Comment by jrwren** [comment]
👍

**Comment by hatched** [comment]
:+1: On the code, no qa.

**Comment by jaycee** [comment]
QA notes:

Deploying against xenial worked, but no password was printed. Full output:

```bash
$ make deploy
tests/00-setup
tests/.venv/bin/python tests/deploy.py
DEBUG:root:setting up the charm
DEBUG:root:deploying juju-gui (series: xenial) from /tmp/tmplSQss8
DEBUG:root:exposing juju-gui
DEBUG:root:waiting for the unit to be ready
{
  "machine": "0", 
  "open-ports": [
    "80/tcp", 
    "443/tcp"
  ], 
  "public-address": "54.161.21.90", 
  "juju-status": {
    "current": "idle", 
    "since": "27 May 2016 15:10:21Z", 
    "version": "2.0-beta8.1"
  }, 
  "workload-status": {
    "current": "unknown", 
    "since": "27 May 2016 15:10:20Z"
  }
}
```

Trusty deploy is pending.

**Comment by jaycee** [comment]
...it seems despite checking out this branch to qa, I ran from develop, which would explain the output being wrong.

**Comment by jaycee** [comment]
QA notes:

Both deploy properly and (now that I'm using the right branch) show the password.

QA :OK:

**Comment by frankban** [comment]
Thank you all for the reviews and QA!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
