### PR TITLE
Use updated juju-deployer to access the new charmstore.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by bac** [comment]
See https://bugs.launchpad.net/juju-quickstart/+bug/1532005

QA: 

You can publish a version of this charm to your namespace and then use it with juju quickstart to ensure that it works.  The following bundle has a charm that is only published to the new charmstore so it is a good test.  Quickstart should deploy both charms.

```
services:
  ubuntu:
    charm: cs:trusty/ubuntu-5
  bui:
    charm: cs:trusty/benchmark-gui-0
series: trusty
```

It can be invoked like:
```
juju quickstart --gui-charm-url=cs:~bac/development/trusty/juju-gui-0 --upload-tools test.yam
```

You should also deploy this charm and ensure you can deploy charms that have been ingested and those that are only published directly to the new charmstore.

**Comment by bac** [comment]
Note this change is related to the issue https://github.com/CanonicalLtd/charmstore-client/issues/155

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/5/
Test PASSed.

**Comment by jaycee** [comment]
Update looks :+1:; trying QA now.

**Comment by jaycee** [comment]
QA:

Using the provided bundle I ran quickstart; everything came up and the bundle deployed fine.

I was also able to deploy a mix of other charms.

QA OK.

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
