### PR TITLE
Fix NRPE version check.

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/163/
Test PASSed.

**Comment by bac** [comment]
In production, there is a persistent failure:

```
cdo-prodstack-jujucharms-jc-jujugui-0[app-is-accessible] CRITICAL	2016-10-03 15:18:35	252d 3h 11m 20s	juju-gui did not return content indicating it was loading. 
```

Since the version checking for jujucharms was recently updated it makes sense to put this ongoing failure to rest.

QA:

1. deploy the charm
1. download locally nrpe-master-external from IS and deploy it.
1. relate the two
1. juju ssh to the gui and run 

```
/var/lib/juju/agents/unit-juju-gui-0/charm/files/nrpe-external-master/check-app-access.sh
All Good
```

**Comment by bac** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
