### PR TITLE
Remove the juju-gui-source config option and related code.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

Deploy the charm into a bootstrapped environment. It should get to a running charm w/o difficulty.

Confirm the juju-gui-source setting is gone.

Monkey with other settings, and if you like upgrade the charm--everything should work without error.

**Comment by hatched** [comment]
:+1: But I notice that that code used git but the git install wasn't removed. Is it still being used elsewhere or was this just an oversight?

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/4/
Test PASSed.

**Comment by jaycee** [comment]
@hatched yeah, the git install could be removed as well, and has been.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/6/
Test PASSed.

**Comment by makyo** [comment]
:+1:

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
