### PR TITLE
Properly include /ws in the WebSocket template.

### PR DESCRIPTION
**Pull request by frankban**
Also note that a development (unreleased) version of the GUI tarball is now used.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/43/
Test FAILed.

**Comment by jaycee** [comment]
:+1: 

Test is failing b/c development gui includes a change to the base_url default. This works fine with the charm as is (it passed QA with the charm) but this test evidently needs to be updated for the new value.

**Comment by bac** [comment]
:+1: but please change the tarball name to releases/jujugui-2.0.2-dev.tar.bz2

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/45/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/46/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/47/
Test PASSed.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
