### PR TITLE
Remove now unnecessary apiUrl placeholder.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

* Checkout this juju GUI PR: https://github.com/juju/juju-gui/pull/1281
* Use that checkout to generate the package for this charm:
```
JUJU_GUI_BRANCH=/path/to/the/PR make clean package
```
* Bootstrap the environment of your choice
* Deploy the charm
```
make deploy
```
* Ensure the charm deploys properly and that the gui is running and works (e.g. you can deploy and configure services etc)
* Turn on sandbox
```
juju set juju-gui sandbox=true
```
* Check that the gui runs normally with sandbox enabled

Using the

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/20/
Test PASSed.

**Comment by hatched** [comment]
:+1: :ok: 
All appears to work as expected in both the real env and in sandbox mode. Thanks for this cleanup!

**Comment by huwshimi** [comment]
Code :+1:

**Comment by hatched** [comment]
:shipit:

**Comment by jaycee** [comment]
Thanks all. :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
