### PR TITLE
Updated expected key for juju status in juju 2

### PR DESCRIPTION
**Pull request by bac**

### CODE REVIEW

**Comment by bac** [comment]
QA using juju 2:

```
juju bootstrap lxd lxd
make deploy
```

Ensure no traceback is printed and the gui deploys a-ok.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/116/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by hatched** [comment]
:+1:

**Comment by bac** [comment]
Thanks for the reviews @frankban and @hatched.  Looking at what I've done I think I'll change it back to use direct key lookup rather than `.get()`. What I have now will go into an endless loop should the `juju-status` key not be there. A traceback is preferable in the case the status output changes again.

**Comment by bac** [comment]
:shipit: 

Self QA. Don't hate me.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/117/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
