### PR TITLE
Add gzip compression config option.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

You must use this with the up to date HEAD of the `develop` branch of http://github.com/juju/juju-gui.

First build the charm with `develop`.
```
JUJU_GUI_BRANCH=/path/to/juju-gui/repo make clean package
```

Then bootstrap your env of choice and `make deploy` the charm.

First, confirm that the gzip compression is on--check the network tab in your browser's developer tools. You'll see less data transferred than the full file size for each file.

Turn off gzip compression:

```
juju set juju-gui gzip-compression=false
```

Now refresh the gui and in the network tab confirm that you are seeing transfer sizes equal to file sizes, showing that gzip compression is off.

Turn it back on and make sure it's still working.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/10/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by jrwren** [comment]
:+1: QA works.  Also confirmed `content-encoding:gzip` when `gzip-compression=true`

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge/8

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/18/
Test PASSed.

**Pull request merged**
