### PR TITLE
GUI server proxy: add support for connecting to Juju 2.0.

### PR DESCRIPTION
**Pull request by frankban**
Also include latest development release of the Juju GUI.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/49/
Test PASSed.

**Comment by bac** [comment]
:+1: but no QA

**Comment by jaycee** [comment]
QA notes:

I deployed against a local env in juju 1.25.3. When I try to go the gui I see

```
Firefox can't establish a connection to the server at wss://10.0.2.88/api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e.
```

Looks like it's using the wrong template, maybe?

**Comment by jaycee** [comment]
```
ubuntu@jc-local-machine-1:~$ sudo tailf /var/log/upstart/guiserver.log 
[I 160225 10:27:31 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 17.04ms
[I 160225 10:27:32 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 15.98ms
[I 160225 10:27:33 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.37ms
[I 160225 10:27:35 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.84ms
[I 160225 10:27:36 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.47ms
[I 160225 10:27:37 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 15.79ms
[I 160225 10:27:39 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.68ms
[I 160225 10:27:41 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 20.69ms
[I 160225 10:27:44 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.44ms
[I 160225 10:27:50 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 16.50ms
```

**Comment by jaycee** [comment]
Further tailf:

```
[I 160225 10:37:16 wsgi:329] 200 GET / (10.0.2.1) 20.06ms
[I 160225 10:37:17 wsgi:329] 200 GET /config.js (10.0.2.1) 4.04ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/oop/oop-min.js&app/assets/javascripts/yui/event-custom-base/event-custom-base-min.js&app/assets/javascripts/yui/event-custom-complex/event-custom-complex-min.js&app/assets/javascripts/yui/intl/intl-min.js&app/utils/changes-utils-min.js&app/assets/javascripts/yui/attribute-core/attribute-core-min.js&app/assets/javascripts/yui/attribute-observable/attribute-observable-min.js&app/assets/javascripts/yui/attribute-extras/attribute-extras-min.js&app/assets/javascripts/yui/attribute-base/attribute-base-min.js&app/assets/javascripts/yui/base-core/base-core-min.js&app/assets/javascripts/yui/base-observable/base-observable-min.js&app/assets/javascripts/yui/base-base/base-base-min.js&app/assets/javascripts/yui/base-build/base-build-min.js&app/assets/javascripts/yui/escape/escape-min.js&app/assets/javascripts/yui/json-parse/json-parse-min.js&app/assets/javascripts/yui/model/model-min.js&app/assets/javascripts/yui/array-extras/array-extras-min.js (10.0.2.1) 30.46ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/event-key/event-key-min.js&app/assets/javascripts/yui/event-outside/event-outside-min.js&app/assets/javascripts/yui/widget-autohide/widget-autohide-min.js&app/assets/javascripts/yui/button-core/button-core-min.js&app/assets/javascripts/yui/button-plugin/button-plugin-min.js&app/assets/javascripts/yui/widget-stdmod/widget-stdmod-min.js&app/assets/javascripts/yui/widget-buttons/widget-buttons-min.js&app/assets/javascripts/yui/widget-modality/widget-modality-min.js&app/assets/javascripts/yui/widget-position/widget-position-min.js&app/assets/javascripts/yui/widget-position-align/widget-position-align-min.js&app/assets/javascripts/yui/widget-position-constrain/widget-position-constrain-min.js&app/assets/javascripts/yui/widget-stack/widget-stack-min.js&app/assets/javascripts/yui/panel/panel-min.js&app/assets/javascripts/yui/json-stringify/json-stringify-min.js&app/assets/javascripts/yui/datatype-date-format/lang/datatype-date-format_en-US.js (10.0.2.1) 24.16ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/node-pluginhost/node-pluginhost-min.js&app/assets/javascripts/yui/color-base/color-base-min.js&app/assets/javascripts/yui/dom-style/dom-style-min.js&app/assets/javascripts/yui/dom-screen/dom-screen-min.js&app/assets/javascripts/yui/node-screen/node-screen-min.js&app/assets/javascripts/yui/node-style/node-style-min.js&app/assets/javascripts/yui/view/view-min.js&app/assets/javascripts/yui/attribute-complex/attribute-complex-min.js&app/assets/javascripts/yui/base-pluginhost/base-pluginhost-min.js&app/assets/javascripts/yui/classnamemanager/classnamemanager-min.js&app/assets/javascripts/yui/event-synthetic/event-synthetic-min.js&app/assets/javascripts/yui/event-focus/event-focus-min.js&app/assets/javascripts/yui/widget-base/widget-base-min.js&app/assets/javascripts/yui/widget-htmlparser/widget-htmlparser-min.js&app/assets/javascripts/yui/widget-skin/widget-skin-min.js&app/assets/javascripts/yui/widget-uievents/widget-uievents-min.js (10.0.2.1) 24.19ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/querystring-parse/querystring-parse-min.js&app/assets/javascripts/yui/querystring-stringify/querystring-stringify-min.js&app/views/state-min.js&app/assets/javascripts/yui/array-invoke/array-invoke-min.js&app/assets/javascripts/yui/arraylist/arraylist-min.js&app/assets/javascripts/yui/model-list/model-list-min.js&app/assets/javascripts/yui/dom-core/dom-core-min.js&app/assets/javascripts/yui/dom-base/dom-base-min.js&app/assets/javascripts/yui/selector-native/selector-native-min.js&app/assets/javascripts/yui/selector/selector-min.js&app/assets/javascripts/yui/node-core/node-core-min.js&app/assets/javascripts/yui/node-base/node-base-min.js&app/assets/javascripts/yui/event-base/event-base-min.js&app/assets/javascripts/yui/event-delegate/event-delegate-min.js&app/assets/javascripts/yui/node-event-delegate/node-event-delegate-min.js&app/assets/javascripts/yui/pluginhost-base/pluginhost-base-min.js&app/assets/javascripts/yui/pluginhost-config/pluginhost-config-min.js (10.0.2.1) 32.40ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/datatype-date-format/datatype-date-format-min.js&app/views/utils-min.js&app/models/entity-extension-min.js&app/models/charm-min.js&app/models/bundle-min.js&app/assets/javascripts/yui/lazy-model-list/lazy-model-list-min.js&app/assets/javascripts/yui/datasource-local/datasource-local-min.js&app/assets/javascripts/yui/querystring-stringify-simple/querystring-stringify-simple-min.js&app/assets/javascripts/yui/io-base/io-base-min.js&app/assets/javascripts/yui/datasource-io/datasource-io-min.js&app/assets/javascripts/yui/plugin/plugin-min.js&app/assets/javascripts/yui/dataschema-base/dataschema-base-min.js&app/assets/javascripts/yui/dataschema-json/dataschema-json-min.js&app/assets/javascripts/yui/datasource-jsonschema/datasource-jsonschema-min.js&app/models/handlers-min.js&app/models/endpoints-min.js&app/assets/javascripts/reconnecting-websocket-min.js&app/store/env/base-min.js&app/store/env/go-min.js&app/assets/javascripts/yui/timers/timers-min.js (10.0.2.1) 43.85ms
[I 160225 10:37:20 wsgi:329] 200 GET /2.0.3/combo?app/components/entity-content/entity-content-min.js&app/components/entity-content-diagram/entity-content-diagram-min.js&app/components/spinner/spinner-min.js&app/components/entity-details/entity-details-min.js&app/components/mid-point/mid-point-min.js&app/components/search-results-item/search-results-item-min.js&app/components/search-results/search-results-select-filter-min.js&app/components/search-results-type-filter/search-results-type-filter-min.js&app/components/search-results/search-results-min.js&app/components/store/store-min.js&app/components/charmbrowser/charmbrowser-min.js&app/components/deployment-bar-notification/deployment-bar-notification-min.js&app/components/added-services-list-item/added-services-list-item-min.js&app/components/added-services-list/added-services-list-min.js&app/components/panel/panel-min.js&app/components/deployment-bar/deployment-bar-min.js&app/components/deployment-summary-change-item/deployment-summary-change-item-min.js (10.0.2.1) 19.23ms
[I 160225 10:37:21 wsgi:329] 200 GET /2.0.3/combo?app/assets/javascripts/yui/promise/promise-min.js&app/models/models-min.js&app/store/endpoints-min.js&app/assets/javascripts/yui/cookie/cookie-min.js&app/store/env/web-handler-min.js&app/assets/javascripts/yui-macaroon-min.js&app/assets/javascripts/js-yaml.min-min.js&app/assets/javascripts/zip-min.js&app/utils/zip-utils-min.js&app/utils/jujulib-conversion-utils-min.js&app/store/env/fakebackend-min.js&app/store/env/sandbox-min.js&app/store/env/web-sandbox-min.js&app/assets/javascripts/yui/event-mousewheel/event-mousewheel-min.js&app/assets/javascripts/yui/event-mouseenter/event-mouseenter-min.js&app/assets/javascripts/yui/event-resize/event-resize-min.js&app/assets/javascripts/yui/event-hover/event-hover-min.js&app/assets/javascripts/yui/event-touch/event-touch-min.js&app/assets/javascripts/yui/event-move/event-move-min.js&app/assets/javascripts/yui/event-flick/event-flick-min.js&app/assets/javascripts/yui/event-valuechange/event-valuechange-min.js (10.0.2.1) 89.22ms
[I 160225 10:37:26 wsgi:329] 200 GET /api/10.0.2.1/17070/d40d7233-f023-4611-8709-7b86bfef280e (10.0.2.1) 15.96ms
```

And frames in chrome:

2016-02-25-103905_963x653_scrot

**Comment by jaycee** [comment]
After we resolved that there was a stale build artifact in my local charm repository, this QAs :ok: against 1.25.3.

:+1: thanks @frankban.

**Comment by frankban** [comment]
Thank you both!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
