### PR TITLE
Remove charm store and JEM API path options.

### PR DESCRIPTION
**Pull request by frankban**
Also rename jem-location to jem-url so that it's more consistent with charmstore-url and other similar values.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/122/
Test PASSed.

**Comment by hatched** [comment]
:+1: Thanks for this cleanup
no qa

**Comment by bac** [comment]
I checked out https://github.com/juju/juju-gui/pull/1628 to $HOME/git/juju-gui

In this version of juju-gut-charm I ran 
```
$ JUJU_GUI_BRANCH=$HOME/git/juju-gui make package
$ juju version
2.0-beta7-xenial-amd64
$ juju bootstrap lxd lxd --upload-tools
$ juju deploy . --series=trusty
$ export JUJU_JEM=https://api.staging.jujucharms.com/jem/
$ juju set-config juju-gui jem-url=$JUJU_JEM
```

I was then able to hit the juju-gui deployed by the charm and see my existing models that I already had running.  I removed the models from the controller, reloaded the GUI, and saw they were gone.

So it seems the configuration settings for the gui and the charm have been changed and work together.

Thanks!

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
