### PR TITLE
Use tornado/upstart config mechanisms rather than production.ini

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
QA:

In your env of choice:
`make deploy` or deploy as a local charm. Confirm the gui works as expected--search, inspector, machine view, deploys, etc.

**Comment by bac** [comment]
`make lint` fails

**Comment by bac** [comment]
This looks great.  :+1:
Will QA shortly.

**Comment by bac** [comment]
QA-OK.  I 'juju set' the debug values back and forth and saw the upstart file change.  Everything worked as expected.

**Comment by jaycee** [comment]
@bac Thanks, I'll fix the lint issues that were exposed and then get this landed.

**Comment by jaycee** [comment]
Everything appears to be sorted. Landing.

**Pull request merged**
