### PR TITLE
Update import statement for new charmhelpes.

### PR DESCRIPTION
**Pull request by jaycee**

### CODE REVIEW

**Comment by jaycee** [comment]
Deploy this branch and apache and form a website relation hook with apache. Nothing should fail.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui-charm/81/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by jrwren** [comment]
:+1:

**Comment by jaycee** [comment]
Fixes #49.

**Comment by jaycee** [comment]
We can skip QA as this fix was cowboyed on GUIMAAS earlier and resolved the issue.

**Comment by jaycee** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-charm-merge

**Pull request merged**
